$(document).ready(function(){
	$(".a1").click(function(){
		$(".a1").hide(function(){
			$("#pr1").show(function(){
				$(".sh2").show(function(){
					$(".a2").click(function(){
						$(".a2").hide(function(){
							$("#pr2").show();
						});
					});
				});
			});
		});
	});
});