$(document).ready(function(){
	$(".a1").click(function(){
		$(".a1").hide(function(){
			$("#pr1").show(function(){
				$("#q2").show();
				$(".a2").show(function(){	
					$("#n2").click(function(){
						$(".a2").hide();
						$("#pr21").show();
					});
					$("#y2").click(function(){
						$(".a2").hide();
						$("#pr2").show();
					});
					
				});
			});
		});
	});
});